### ISSUE TITLE
MemoryError in consolidate_node

### ISSUE THREAD

**Issue by moi90** [morphocluster/morphocluster#56]
```
  -3.93241427e-01  9.50747351e-02  7.11707847e-02 -7.21649441e-04
  -3.12505170e-01  3.12774557e-01  3.15517310e-01 -2.01944135e-01
   2.00376051e-01  2.37251354e-01 -5.02645016e-02 -2.32518662e-02
   2.87209255e-03 -3.13420044e-01  3.00367089e-02 -1.26006014e-01
  -2.54488679e-01  1.49026718e-01  1.79387295e-01 -2.17604360e-02
  -3.09809039e-01 -1.67408256e-01  6.91987036e-02 -5.25163874e-02]]
Error processing node 15357
consolidate_node: 373815.873s
  15338x get_objects: 373384.597s (99%)
  15338x _prototypes: 350.945s (0%)
  15338x _centroid: 9.407s (0%)
  15338x _calc_own_type_objects: 8.689s (0%)
      1x read_sql_query: 3.660s (0%)
  15338x _calc_type_objects: 0.716s (0%)
Traceback (most recent call last):
  File "/opt/conda/envs/morphocluster/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/code/morphocluster/cli.py", line 248, in load_project
    tree.consolidate_node(root_id)
  File "/code/morphocluster/tree.py", line 1638, in consolidate_node
    _prototypes, N_PROTOTYPES
  File "/code/morphocluster/processing/prototypes.py", line 207, in merge_prototypes
    labels = clusterer.fit_predict(prototypes_)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/sklearn/base.py", line 357, in fit_predict
    self.fit(X)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/sklearn/cluster/hierarchical.py", line 831, in fit
    **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/sklearn/externals/joblib/memory.py", line 342, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/sklearn/cluster/hierarchical.py", line 585, in _complete_linkage
    return linkage_tree(*args, **kwargs)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/sklearn/cluster/hierarchical.py", line 471, in linkage_tree
    out = hierarchy.linkage(X, method=linkage, metric=affinity)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 1060, in linkage
    y = distance.pdist(y, metric)
  File "/opt/conda/envs/morphocluster/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2250, in pdist
    return pdist_fn(X, out=out, **kwargs)
numpy.core._exceptions.MemoryError: Unable to allocate 224. GiB for an array with shape (30112420528,) and data type float64
```

**Comment by moi90** [comment]
7,972,159 images in total. (27.9 GB)
